root: true

extends:
  - pegasus
  - pegasus/node
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:react-hooks/recommended

parser: '@babel/eslint-parser'

plugins:
  - jest

rules:
  react/prop-types: off
  jsx-quotes:
    - error
    - prefer-single

overrides:
  - files: scripts/*.js
    rules:
      no-console: off

env:
  browser: true
  jest/globals: true
