root: true

extends:
  - pegasus
  - pegasus/node
  - plugin:react/recommended

parser: '@babel/eslint-parser'

plugins:
  - react-hooks
  - jest

rules:
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  react/prop-types: off
  jsx-quotes:
    - error
    - prefer-single

overrides:
  - files: gulpfile.js
    rules:
      no-console: off

env:
  browser: true
  jest/globals: true

settings:
  react:
    pragma: React
    version: detect
